#!/bin/bash
# Display carbon-pipeline project information

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Carbon Pipeline Project Information"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📦 Project: carbon-pipeline"
echo "🌿 Branch: main"
echo "📍 Location: .unison/v2/"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Quick Access"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📖 Documentation:"
echo "   • CLAUDE.md - Claude Code development guide"
echo "   • MCP_CONFIGURATION.md - MCP server reference"
echo "   • CARBON_PIPELINE_PROJECT.md - Project details"
echo "   • README.md - Main project README"
echo ""
echo "📝 Source Files:"
echo "   • carbonIntensity.u - Core types and utilities"
echo "   • cleanDecoder.u - JSON decoder"
echo "   • aggregations.u - Statistical functions"
echo ""
echo "🧪 Test Files:"
echo "   • testAggregations - Test aggregation functions"
echo "   • testCleanDecoder - Test JSON decoder"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  MCP Development"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "With Claude Code, use MCP tools:"
echo ""
echo "  mcp__unison__list-project-definitions({"
echo "    projectContext: {projectName: \"carbon-pipeline\", branchName: \"main\"}"
echo "  })"
echo ""
echo "  mcp__unison__run({"
echo "    projectContext: {projectName: \"carbon-pipeline\", branchName: \"main\"},"
echo "    mainFunctionName: \"testAggregations\","
echo "    args: []"
echo "  })"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Manual UCM"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Start UCM:"
echo "  $ ucm"
echo ""
echo "Inside UCM:"
echo "  .> ls                      # List definitions"
echo "  .> run testAggregations    # Run tests"
echo "  .> find average            # Search for definitions"
echo ""
